export type LocationData = Record<string, Record<string, string[]>>;

export const LOCATIONS: LocationData = {
  "México": {
    "Aguascalientes":["Aguascalientes","Calvillo","Cosío","Jesús María","Pabellón de Arteaga","Rincón de Romos","San José de Gracia","Tepezalá","El Llano","Asientos"],
    "Baja California":["Tijuana","Mexicali","Ensenada","Tecate","Playas de Rosarito","San Quintín"],
    "Baja California Sur":["La Paz","Los Cabos","Loreto","Mulegé","Comondú"],
    "Campeche":["Campeche","Ciudad del Carmen","Champotón","Calkiní","Escárcega"],
    "Chiapas":["Tuxtla Gutiérrez","San Cristóbal de las Casas","Tapachula","Comitán","Ocosingo","Palenque","Tonalá"],
    "Chihuahua":["Chihuahua","Ciudad Juárez","Delicias","Cuauhtémoc","Parral","Ojinaga","Nuevo Casas Grandes"],
    "Ciudad de México":["Álvaro Obregón","Azcapotzalco","Benito Juárez","Coyoacán","Cuajimalpa","Cuauhtémoc","Gustavo A. Madero","Iztacalco","Iztapalapa","Magdalena Contreras","Miguel Hidalgo","Milpa Alta","Tláhuac","Tlalpan","Venustiano Carranza","Xochimilco"],
    "Coahuila":["Saltillo","Torreón","Monclova","Piedras Negras","Acuña","Ramos Arizpe","San Pedro"],
    "Colima":["Colima","Manzanillo","Tecomán","Villa de Álvarez","Armería","Comala"],
    "Durango":["Durango","Gómez Palacio","Lerdo","Santiago Papasquiaro","El Salto","Pueblo Nuevo"],
    "Estado de México":["Toluca","Ecatepec","Naucalpan","Nezahualcóyotl","Tlalnepantla","Chimalhuacán","Ixtapaluca","Atizapán de Zaragoza","Coacalco","Tultitlán","Cuautitlán Izcalli","Texcoco","Metepec","Chalco"],
    "Guanajuato":["León","Irapuato","Celaya","Guanajuato","Salamanca","Silao","San Miguel de Allende","Dolores Hidalgo"],
    "Guerrero":["Acapulco","Chilpancingo","Zihuatanejo","Taxco","Iguala"],
    "Hidalgo":["Pachuca","Tulancingo","Tula de Allende","Actopan","Huejutla","Ixmiquilpan"],
    "Jalisco":["Guadalajara","Zapopan","Tlaquepaque","Tonalá","Tlajomulco","Puerto Vallarta","Lagos de Moreno","Tepatitlán","Ocotlán","Ciudad Guzmán"],
    "Michoacán":["Morelia","Uruapan","Zamora","Lázaro Cárdenas","Pátzcuaro","Apatzingán","Los Reyes","Zitácuaro"],
    "Morelos":["Cuernavaca","Jiutepec","Cuautla","Temixco","Yautepec","Jojutla"],
    "Nayarit":["Tepic","Bahía de Banderas","Santiago Ixcuintla","Acaponeta","Compostela"],
    "Nuevo León":["Monterrey","Guadalupe","San Nicolás de los Garza","Apodaca","General Escobedo","Santa Catarina","San Pedro Garza García","Linares","Montemorelos"],
    "Oaxaca":["Oaxaca de Juárez","Salina Cruz","Juchitán","Tuxtepec","Huatulco","Puerto Escondido"],
    "Puebla":["Puebla","Tehuacán","San Martín Texmelucan","Atlixco","Izúcar de Matamoros","Cholula","Teziutlán"],
    "Querétaro":["Querétaro","San Juan del Río","Corregidora","El Marqués","Tequisquiapan"],
    "Quintana Roo":["Cancún","Playa del Carmen","Chetumal","Tulum","Cozumel","Isla Mujeres"],
    "San Luis Potosí":["San Luis Potosí","Ciudad Valles","Matehuala","Rioverde","Tamazunchale"],
    "Sinaloa":["Culiacán","Mazatlán","Los Mochis","Guasave","Navolato"],
    "Sonora":["Hermosillo","Ciudad Obregón","Navojoa","Nogales","San Luis Río Colorado","Guaymas"],
    "Tabasco":["Villahermosa","Cárdenas","Comalcalco","Macuspana","Paraíso"],
    "Tamaulipas":["Reynosa","Matamoros","Nuevo Laredo","Tampico","Ciudad Victoria","Altamira"],
    "Tlaxcala":["Tlaxcala","Apizaco","Huamantla","Chiautempan","Calpulalpan"],
    "Veracruz":["Veracruz","Xalapa","Coatzacoalcos","Boca del Río","Poza Rica","Córdoba","Orizaba","Tuxpan"],
    "Yucatán":["Mérida","Valladolid","Tizimín","Kanasín","Progreso","Umán"],
    "Zacatecas":["Zacatecas","Guadalupe","Fresnillo","Jerez","Río Grande"],
  },
  "Estados Unidos": {
    "California":["Los Ángeles","San Francisco","San Diego","Sacramento","San José","Fresno","Oakland","Long Beach"],
    "Texas":["Houston","Dallas","San Antonio","Austin","Fort Worth","El Paso","Arlington","Corpus Christi","Laredo"],
    "Florida":["Miami","Orlando","Tampa","Jacksonville","St. Petersburg","Hialeah","Tallahassee","Fort Lauderdale"],
    "New York":["Nueva York","Buffalo","Rochester","Yonkers","Syracuse","Albany"],
    "Illinois":["Chicago","Aurora","Rockford","Joliet","Naperville","Springfield"],
    "Arizona":["Phoenix","Tucson","Mesa","Chandler","Scottsdale","Tempe"],
    "Georgia":["Atlanta","Augusta","Columbus","Macon","Savannah"],
    "Washington":["Seattle","Spokane","Tacoma","Bellevue","Everett"],
    "Nevada":["Las Vegas","Henderson","Reno","North Las Vegas"],
    "Colorado":["Denver","Colorado Springs","Aurora","Fort Collins","Lakewood"],
    "Otro estado":["Otra ciudad"],
  },
  "España": {
    "Madrid":["Madrid","Alcalá de Henares","Leganés","Getafe","Alcorcón","Móstoles"],
    "Cataluña":["Barcelona","Hospitalet de Llobregat","Terrassa","Badalona","Sabadell","Lleida"],
    "Andalucía":["Sevilla","Málaga","Córdoba","Granada","Almería","Cádiz"],
    "Comunidad Valenciana":["Valencia","Alicante","Elche","Castellón","Torrent"],
    "País Vasco":["Bilbao","Vitoria-Gasteiz","San Sebastián","Barakaldo"],
    "Galicia":["Vigo","A Coruña","Ourense","Pontevedra","Lugo"],
    "Castilla y León":["Valladolid","Burgos","Salamanca","León","Segovia"],
    "Otra comunidad":["Otra ciudad"],
  },
  "Colombia": {
    "Bogotá D.C.":["Bogotá","Usaquén","Chapinero","Kennedy","Suba","Bosa"],
    "Antioquia":["Medellín","Bello","Itagüí","Envigado","Apartadó","Rionegro"],
    "Valle del Cauca":["Cali","Buenaventura","Palmira","Tuluá","Buga"],
    "Cundinamarca":["Soacha","Zipaquirá","Facatativá","Chía","Fusagasugá"],
    "Atlántico":["Barranquilla","Soledad","Malambo","Sabanalarga"],
    "Santander":["Bucaramanga","Floridablanca","Girón","Piedecuesta"],
    "Otro departamento":["Otra ciudad"],
  },
  "Argentina": {
    "Buenos Aires (Ciudad)":["Buenos Aires","Palermo","San Telmo","Belgrano","Recoleta","La Boca"],
    "Buenos Aires (Provincia)":["La Plata","Mar del Plata","Quilmes","Lanús","Lomas de Zamora","Morón","Tigre"],
    "Córdoba":["Córdoba","Villa María","Río Cuarto","San Francisco","Villa Carlos Paz"],
    "Santa Fe":["Rosario","Santa Fe","Rafaela","Venado Tuerto"],
    "Mendoza":["Mendoza","San Rafael","Godoy Cruz","Guaymallén","Luján de Cuyo"],
    "Otra provincia":["Otra ciudad"],
  },
  "Brasil":{"São Paulo":[],"Río de Janeiro":[],"Bahía":[],"Minas Gerais":[],"Paraná":[],"Rio Grande do Sul":[],"Otro estado":[]},
  "Chile":{"Santiago":[],"Valparaíso":[],"Biobío":[],"Maule":[],"Araucanía":[],"Otra región":[]},
  "Perú":{"Lima":[],"Arequipa":[],"La Libertad":[],"Cusco":[],"Piura":[],"Otro departamento":[]},
  "Venezuela":{"Caracas":[],"Zulia":[],"Miranda":[],"Carabobo":[],"Aragua":[],"Otro estado":[]},
  "Ecuador":{"Pichincha":[],"Guayas":[],"Azuay":[],"Manabí":[],"El Oro":[],"Otra provincia":[]},
  "Bolivia":{"La Paz":[],"Santa Cruz":[],"Cochabamba":[],"Oruro":[],"Potosí":[],"Otro departamento":[]},
  "Paraguay":{"Asunción":[],"Central":[],"Alto Paraná":[],"Itapúa":[],"Otro departamento":[]},
  "Uruguay":{"Montevideo":[],"Canelones":[],"Maldonado":[],"Salto":[],"Otro departamento":[]},
  "Guatemala":{"Guatemala":[],"Quetzaltenango":[],"Escuintla":[],"Huehuetenango":[],"Otro departamento":[]},
  "Honduras":{"Francisco Morazán":[],"Cortés":[],"Yoro":[],"Comayagua":[],"Otro departamento":[]},
  "El Salvador":{"San Salvador":[],"Santa Ana":[],"San Miguel":[],"La Libertad":[],"Otro departamento":[]},
  "Nicaragua":{"Managua":[],"Chinandega":[],"León":[],"Matagalpa":[],"Otro departamento":[]},
  "Costa Rica":{"San José":[],"Alajuela":[],"Cartago":[],"Heredia":[],"Otra provincia":[]},
  "Panamá":{"Panamá":[],"Chiriquí":[],"Colón":[],"Veraguas":[],"Otra provincia":[]},
  "Cuba":{"La Habana":[],"Santiago de Cuba":[],"Holguín":[],"Camagüey":[],"Otra provincia":[]},
  "República Dominicana":{"Distrito Nacional":[],"Santiago":[],"Santo Domingo":[],"La Vega":[],"Otra provincia":[]},
  "Puerto Rico":{"San Juan":[],"Bayamón":[],"Carolina":[],"Ponce":[],"Otro municipio":[]},
  "Francia":{"Île-de-France":[],"Provenza-Alpes-Costa Azul":[],"Auvernia-Ródano-Alpes":[],"Occitania":[],"Otra región":[]},
  "Italia":{"Lombardía":[],"Lacio":[],"Campania":[],"Sicilia":[],"Véneto":[],"Otra región":[]},
  "Alemania":{"Baviera":[],"Renania del Norte-Westfalia":[],"Berlín":[],"Hamburgo":[],"Baden-Württemberg":[],"Otro estado":[]},
  "Portugal":{"Lisboa":[],"Oporto":[],"Braga":[],"Setúbal":[],"Faro":[],"Otro distrito":[]},
  "Reino Unido":{"Inglaterra":[],"Escocia":[],"Gales":[],"Irlanda del Norte":[]},
  "Canadá":{"Ontario":[],"Quebec":[],"Columbia Británica":[],"Alberta":[],"Manitoba":[],"Otra provincia":[]},
  "Australia":{"Nueva Gales del Sur":[],"Victoria":[],"Queensland":[],"Australia Occidental":[],"Australia del Sur":[],"Otro estado":[]},
  "Nueva Zelanda":{"Auckland":[],"Wellington":[],"Canterbury":[],"Otra región":[]},
  "China":{"Pekín":[],"Shanghái":[],"Guangdong":[],"Sichuan":[],"Henan":[],"Otra provincia":[]},
  "Japón":{"Tokio":[],"Osaka":[],"Kanagawa":[],"Aichi":[],"Saitama":[],"Otra prefectura":[]},
  "Corea del Sur":{"Seúl":[],"Busan":[],"Incheon":[],"Daegu":[],"Otra provincia":[]},
  "India":{"Maharashtra":[],"Delhi":[],"Karnataka":[],"Tamil Nadu":[],"Uttar Pradesh":[],"Otro estado":[]},
  "Filipinas":{"Metro Manila":[],"Cebu":[],"Davao":[],"Otra región":[]},
  "Indonesia":{"Yakarta":[],"Surabaya":[],"Bandung":[],"Otra provincia":[]},
  "Vietnam":{"Hanói":[],"Ciudad Ho Chi Minh":[],"Da Nang":[],"Otra provincia":[]},
  "Tailandia":{"Bangkok":[],"Chiang Mai":[],"Phuket":[],"Otra provincia":[]},
  "Rusia":{"Moscú":[],"San Petersburgo":[],"Novosibirsk":[],"Ekaterimburgo":[],"Otro sujeto federal":[]},
  "Turquía":{"Estambul":[],"Ankara":[],"Esmirna":[],"Bursa":[],"Otra provincia":[]},
  "Ucrania":{"Kiev":[],"Járkov":[],"Odesa":[],"Dnipró":[],"Otra provincia":[]},
  "Polonia":{"Varsovia":[],"Cracovia":[],"Łódź":[],"Breslavia":[],"Otro voivodato":[]},
  "Países Bajos":{"Holanda del Norte":[],"Holanda del Sur":[],"Utrecht":[],"Otra provincia":[]},
  "Bélgica":{"Bruselas":[],"Amberes":[],"Gante":[],"Otra provincia":[]},
  "Suiza":{"Zúrich":[],"Ginebra":[],"Berna":[],"Basilea":[],"Otro cantón":[]},
  "Suecia":{"Estocolmo":[],"Västra Götaland":[],"Skåne":[],"Otro condado":[]},
  "Noruega":{"Oslo":[],"Bergen":[],"Trondheim":[],"Otro condado":[]},
  "Dinamarca":{"Copenhague":[],"Jutlandia":[],"Funen":[],"Otra región":[]},
  "Finlandia":{"Uusimaa":[],"Pirkanmaa":[],"Laponia":[],"Otra región":[]},
  "Grecia":{"Ática":[],"Macedonia Central":[],"Tesalia":[],"Otra región":[]},
  "Egipto":{"El Cairo":[],"Alejandría":[],"Guiza":[],"Otro gobernatorato":[]},
  "Marruecos":{"Casablanca":[],"Rabat":[],"Fez":[],"Marrakech":[],"Otra región":[]},
  "Argelia":{"Argel":[],"Orán":[],"Constantine":[],"Otra provincia":[]},
  "Nigeria":{"Lagos":[],"Abuja":[],"Kano":[],"Rivers":[],"Otro estado":[]},
  "Sudáfrica":{"Gauteng":[],"Ciudad del Cabo":[],"KwaZulu-Natal":[],"Limpopo":[],"Otra provincia":[]},
  "Kenia":{"Nairobi":[],"Mombasa":[],"Kisumu":[],"Otro condado":[]},
  "Ghana":{"Gran Acra":[],"Ashanti":[],"Brong-Ahafo":[],"Otra región":[]},
  "Etiopía":{"Adís Abeba":[],"Amhara":[],"Oromía":[],"Otra región":[]},
  "Israel":{"Tel Aviv":[],"Jerusalén":[],"Haifa":[],"Otro distrito":[]},
  "Arabia Saudita":{"Riad":[],"Yeda":[],"La Meca":[],"Otra región":[]},
  "Emiratos Árabes Unidos":{"Dubái":[],"Abu Dabi":[],"Sharjah":[],"Otro emirato":[]},
  "Irán":{"Teherán":[],"Isfahán":[],"Razaví Jorasán":[],"Otra provincia":[]},
  "Pakistán":{"Punyab":[],"Sindh":[],"Jyber Pajtunjua":[],"Otra provincia":[]},
  "Bangladesh":{"Dhaka":[],"Chittagong":[],"Rajshahi":[],"Otra división":[]},
  "Otro país":{"Otra región":["Otra ciudad"]},
};

export const PAISES = Object.keys(LOCATIONS);

export function getEstados(pais: string): string[] {
  return Object.keys(LOCATIONS[pais] || {});
}

export function getMunicipios(pais: string, estado: string): string[] {
  return LOCATIONS[pais]?.[estado] || [];
}

export function formatLocation(pais?: string, estado?: string, municipio?: string): string {
  const parts = [municipio, estado, pais].filter(Boolean);
  return parts.join(", ");
}
