export type LocationData = Record<string, Record<string, string[]>>;
export const LOCATIONS: LocationData = {
      "Mexico": {
            "Aguascalientes":["Aguascalientes","Calvillo","Jesus Maria","Pabellon de Arteaga","Rincon de Romos"],
                "Baja California":["Tijuana","Mexicali","Ensenada","Tecate"],
                    "Baja California Sur":["La Paz","Los Cabos","Loreto"],
                        "Campeche":["Campeche","Ciudad del Carmen","Champoton"],
                            "Chiapas":["Tuxtla Gutierrez","San Cristobal de las Casas","Tapachula","Comitan","Palenque"],
                                "Chihuahua":["Chihuahua","Ciudad Juarez","Delicias","Cuauhtemoc","Parral"],
                                    "Ciudad de Mexico":["Alvaro Obregon","Azcapotzalco","Benito Juarez","Coyoacan","Cuajimalpa","Cuauhtemoc","Gustavo A. Madero","Iztacalco","Iztapalapa","Miguel Hidalgo","Tlalpan","Xochimilco"],
                                        "Coahuila":["Saltillo","Torreon","Monclova","Piedras Negras","Acuna"],
                                            "Colima":["Colima","Manzanillo","Tecoman","Villa de Alvarez"],
                                                "Durango":["Durango","Gomez Palacio","Lerdo"],
                                                    "Estado de Mexico":["Toluca","Ecatepec","Naucalpan","Nezahualcoyotl","Tlalnepantla","Texcoco","Metepec","Chalco"],
                                                        "Guanajuato":["Leon","Irapuato","Celaya","Guanajuato","Salamanca","San Miguel de Allende"],
                                                            "Guerrero":["Acapulco","Chilpancingo","Zihuatanejo","Taxco"],
                                                                "Hidalgo":["Pachuca","Tulancingo","Tula de Allende"],
                                                                    "Jalisco":["Guadalajara","Zapopan","Tlaquepaque","Tonala","Puerto Vallarta"],
                                                                        "Michoacan":["Morelia","Uruapan","Zamora","Lazaro Cardenas","Patzcuaro"],
                                                                            "Morelos":["Cuernavaca","Jiutepec","Cuautla","Temixco"],
                                                                                "Nayarit":["Tepic","Bahia de Banderas"],
                                                                                    "Nuevo Leon":["Monterrey","Guadalupe","San Nicolas de los Garza","Apodaca","Santa Catarina","San Pedro Garza Garcia"],
                                                                                        "Oaxaca":["Oaxaca de Juarez","Salina Cruz","Juchitan","Tuxtepec","Puerto Escondido"],
                                                                                            "Puebla":["Puebla","Tehuacan","San Martin Texmelucan","Atlixco","Cholula"],
                                                                                                "Queretaro":["Queretaro","San Juan del Rio","Corregidora"],
                                                                                                    "Quintana Roo":["Cancun","Playa del Carmen","Chetumal","Tulum","Cozumel"],
                                                                                                        "San Luis Potosi":["San Luis Potosi","Ciudad Valles","Matehuala"],
                                                                                                            "Sinaloa":["Culiacan","Mazatlan","Los Mochis"],
                                                                                                                "Sonora":["Hermosillo","Ciudad Obregon","Navojoa","Nogales"],
                                                                                                                    "Tabasco":["Villahermosa","Cardenas","Comalcalco"],
                                                                                                                        "Tamaulipas":["Reynosa","Matamoros","Nuevo Laredo","Tampico","Ciudad Victoria"],
                                                                                                                            "Tlaxcala":["Tlaxcala","Apizaco","Huamantla"],
                                                                                                                                "Veracruz":["Veracruz","Xalapa","Coatzacoalcos","Poza Rica","Cordoba","Orizaba"],
                                                                                                                                    "Yucatan":["Merida","Valladolid","Progreso"],
                                                                                                                                        "Zacatecas":["Zacatecas","Fresnillo","Jerez"],
                                                                                                                                          },
                                                                                                                                            "Estados Unidos": {"California":["Los Angeles","San Francisco","San Diego","Sacramento"],"Texas":["Houston","Dallas","San Antonio","Austin","El Paso","Laredo"],"Florida":["Miami","Orlando","Tampa","Jacksonville"],"New York":["Nueva York","Buffalo","Albany"],"Illinois":["Chicago","Aurora"],"Arizona":["Phoenix","Tucson","Mesa"],"Otro estado":[]},
                                                                                                                                              "Espana": {"Madrid":["Madrid","Alcala de Henares","Getafe"],"Cataluna":["Barcelona","Terrassa","Badalona"],"Andalucia":["Sevilla","Malaga","Cordoba","Granada"],"Comunidad Valenciana":["Valencia","Alicante"],"Pais Vasco":["Bilbao","San Sebastian"],"Galicia":["Vigo","A Coruna"],"Otra comunidad":[]},
                                                                                                                                                "Colombia": {"Bogota D.C.":["Bogota"],"Antioquia":["Medellin","Bello","Itagui"],"Valle del Cauca":["Cali","Palmira"],"Atlantico":["Barranquilla","Soledad"],"Otro departamento":[]},
                                                                                                                                                  "Argentina": {"Buenos Aires (Ciudad)":["Buenos Aires","Palermo","Belgrano"],"Buenos Aires (Provincia)":["La Plata","Mar del Plata","Quilmes"],"Cordoba":["Cordoba","Villa Maria"],"Santa Fe":["Rosario","Santa Fe"],"Mendoza":["Mendoza"],"Otra provincia":[]},
                                                                                                                                                    "Brasil":{"Sao Paulo":[],"Rio de Janeiro":[],"Bahia":[],"Minas Gerais":[],"Parana":[],"Otro estado":[]},
                                                                                                                                                      "Chile":{"Santiago":[],"Valparaiso":[],"Biobio":[],"Otra region":[]},
                                                                                                                                                        "Peru":{"Lima":[],"Arequipa":[],"Cusco":[],"Otro departamento":[]},
                                                                                                                                                          "Venezuela":{"Caracas":[],"Zulia":[],"Miranda":[],"Otro estado":[]},
                                                                                                                                                            "Ecuador":{"Pichincha":[],"Guayas":[],"Otra provincia":[]},
                                                                                                                                                              "Bolivia":{"La Paz":[],"Santa Cruz":[],"Cochabamba":[],"Otro departamento":[]},
                                                                                                                                                                "Paraguay":{"Asuncion":[],"Central":[],"Otro departamento":[]},
                                                                                                                                                                  "Uruguay":{"Montevideo":[],"Canelones":[],"Otro departamento":[]},
                                                                                                                                                                    "Guatemala":{"Guatemala":[],"Quetzaltenango":[],"Otro departamento":[]},
                                                                                                                                                                      "Honduras":{"Francisco Morazan":[],"Cortes":[],"Otro departamento":[]},
                                                                                                                                                                        "El Salvador":{"San Salvador":[],"Santa Ana":[],"Otro departamento":[]},
                                                                                                                                                                          "Nicaragua":{"Managua":[],"Leon":[],"Otro departamento":[]},
                                                                                                                                                                            "Costa Rica":{"San Jose":[],"Alajuela":[],"Otra provincia":[]},
                                                                                                                                                                              "Panama":{"Panama":[],"Chiriqui"
      }
}